# -*- coding: utf-8 -*-
"""part7_socialjustice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DxnJvKstG85_ZJZWKkxz60U7E8eGSNGh
"""

import pandas as pd
import matplotlib.pyplot as plt

# Load dataset (cleaned if available)
try:
    df = pd.read_csv("cleaned_items.csv")
except FileNotFoundError:
    df = pd.read_csv("20191226-items.csv")

print("=== Social Justice Impact Analysis ===")

# 1. Price accessibility: check median, quartiles
if 'price' in df.columns:
    price_stats = df['price'].describe()
    print("\nPrice Distribution Summary:")
    print(price_stats)

    # Visualize price distribution
    df['price'].plot(kind="hist", bins=50, title="Price Distribution", log=True)
    plt.xlabel("Price (log scale)")
    plt.show()

# 2. Category inequality
if 'category' in df.columns:
    category_counts = df['category'].value_counts()
    print("\nTop 10 categories by frequency:")
    print(category_counts.head(10))

    category_counts.head(10).plot(kind="bar", title="Top 10 Categories Representation")
    plt.ylabel("Count")
    plt.show()

# 3. Global vs Local brands (proxy for accessibility)
if 'brand' in df.columns:
    # Heuristic: treat brands with very low counts as "local"
    brand_counts = df['brand'].value_counts()
    local_brands = brand_counts[brand_counts < 5].count()
    global_brands = brand_counts[brand_counts >= 5].count()

    print(f"\nGlobal Brands (>=5 items): {global_brands}")
    print(f"Local Brands (<5 items): {local_brands}")

    plt.bar(['Global Brands', 'Local Brands'], [global_brands, local_brands])
    plt.title("Global vs Local Brands Representation")
    plt.ylabel("Number of Brands")
    plt.show()

print("\nSocial Justice analysis completed. Check charts for insights.")