# -*- coding: utf-8 -*-
"""part8_conclusion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O5pgmTn_YCDaC6CjpEF2Rr9PPZFOE7vb
"""

import pandas as pd

# Load dataset (prefer cleaned if available)
try:
    df = pd.read_csv("cleaned_items.csv")
except FileNotFoundError:
    df = pd.read_csv("20191226-items.csv")

print("=== Part 8: Conclusions & Recommendations ===\n")

# 1. Dataset summary
print("Dataset Overview:")
print(f"Rows: {df.shape[0]}, Columns: {df.shape[1]}")
print("\nMissing Values Summary:")
print(df.isnull().sum())

# 2. Key Findings Recap
print("\n--- Key Findings ---")
print("1. Data Cleaning: Missing values in price/brand/category required handling.")
print("2. EDA: Prices showed heavy skew, requiring log-scale visualization.")
print("3. Modeling: Predictive models can estimate missing prices/categories, but must be checked for bias.")
print("4. Ethics: Risks of price manipulation, biased brand representation, and lack of transparency.")
print("5. Social Justice: Dataset skews toward global brands, raising accessibility and inclusivity concerns.")

# 3. Recommendations
print("\n--- Recommendations ---")
print("• Ensure transparency in how prices/categories are predicted.")
print("• Regularly audit models for bias across brands and categories.")
print("• Support local brands by balancing dataset representation.")
print("• Use privacy-preserving techniques when expanding dataset with consumer data.")
print("• Communicate findings responsibly to avoid reinforcing inequalities.")

print("\n=== End of Project ===")