# -*- coding: utf-8 -*-
"""part6_ethics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GHlT12_SAqL5PldAvugj1R0gLPzHZyx9
"""

import pandas as pd
import matplotlib.pyplot as plt

# Load dataset (cleaned if available)
try:
    df = pd.read_csv("cleaned_items.csv")
except FileNotFoundError:
    df = pd.read_csv("20191226-items.csv")

print("=== Ethical Considerations Analysis ===")

# 1. Check for sensitive attributes
sensitive_columns = ['gender', 'race', 'age']
print("\nChecking for sensitive attributes (gender, race, age):")
for col in sensitive_columns:
    if col in df.columns:
        print(f"Column '{col}' exists with {df[col].nunique()} unique values")
    else:
        print(f"Column '{col}' not found (privacy-friendly)")

# 2. Representation fairness: brand frequency
if 'brand' in df.columns:
    brand_counts = df['brand'].value_counts()
    print("\nTop 10 most common brands:")
    print(brand_counts.head(10))
    print("\nBottom 10 least common brands:")
    print(brand_counts.tail(10))

    # Plot brand representation (top 10)
    brand_counts.head(10).plot(kind="bar", title="Top 10 Brands Representation")
    plt.ylabel("Count")
    plt.show()

# 3. Price inequality across brands
if 'price' in df.columns and 'brand' in df.columns:
    brand_price_stats = df.groupby('brand')['price'].mean().sort_values(ascending=False)
    print("\nAverage price per brand (top 10):")
    print(brand_price_stats.head(10))

    # Plot price inequality
    brand_price_stats.head(10).plot(kind="bar", title="Top 10 Brands by Avg Price")
    plt.ylabel("Average Price")
    plt.show()

print("\nEthical analysis completed. Check charts for visual insights.")