import pandas as pd
from modules.models import ModelRunner
from modules.clean import DataHandler
from modules.visualize import DataVisualizer




def main():

    data_path = "case-study\\data\\bank_credit_scoring.csv"

    handler = DataHandler(pd.read_csv(data_path))

    handler.clean_data()

    handler.describe_data('O')
    handler.describe_data('c')


    #Ridge & lasso train, predict, analyze with adjusted training data
    models = ModelRunner(handler.get_cleaned_data())

    # If you would like to view one of the saved models from the case study
    # Uncomment these lines and point to the directory of models you'd like to load
    # models_path = './case-study/biased'
    # models.load_models(file_path=models_path)


    models.train('LIMIT')

    ridge_vis = DataVisualizer(models.predict('R'))
    ridge_vis.compare_genders('TRUE_LIMIT', "Unadjusted Training Data True Limit")
    ridge_vis.compare_genders('PREDICTIONS', "Unadjusted Training Data Ridge Predictions")

    lasso_vis = DataVisualizer(models.predict('L'))
    lasso_vis.compare_genders('PREDICTIONS', "Unadjusted Training Data Lasso Predictions")


    #Oversample data to balance classes
    oversampled = handler.over_sample()
    oversampled_model = ModelRunner(oversampled)

    oversampled_model.train('LIMIT')
    oversampled_vis_r = DataVisualizer(oversampled_model.predict('R'))
    oversampled_vis_r.compare_genders('TRUE_LIMIT', 'Oversampled True Credit Limit')
    oversampled_vis_r.compare_genders('PREDICTIONS','Oversampled Ridge Predictions')

    oversampled_vis_l = DataVisualizer(oversampled_model.predict('L'))
    oversampled_vis_l.compare_genders('PREDICTIONS','Oversampled Lasso Predictions')




    #Undersample data to balance classes
    undersampled = handler.under_sample()
    undersampled_model = ModelRunner(undersampled)


    undersampled_model.train('LIMIT')
    undersampled_vis_r = DataVisualizer(undersampled_model.predict('R'))
    undersampled_vis_r.compare_genders('TRUE_LIMIT','Undersampled True Credit Limit')
    undersampled_vis_r.compare_genders('PREDICTIONS','Undersampled Ridge Predictions')

    undersampled_vis_l = DataVisualizer(undersampled_model.predict('L'))
    undersampled_vis_l.compare_genders('PREDICTIONS','Undersampled Lasso Predictions')


    #If you would like to save the models generated by this code, please uncomment the desired lines
    # models_path = './case-study/biased'
    #models.save_models(file_path=models_path)
    #oversampled_model.save_models(file_path=models_path)
    #undersampled_model.save_models(file_path=models_path)





main()